### ISSUE TITLE
multi day tracks are not showing in schedule 

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2019#108]
with `Mon,Tue` doesn't work

![image](https://user-images.githubusercontent.com/656739/57219522-46131280-6ff0-11e9-8d75-5e2b79c9ec14.png)

with just `Mon` works:

![image](https://user-images.githubusercontent.com/656739/57219538-50cda780-6ff0-11e9-9aa6-378999515734.png)

**Comment by fzipi** [comment]
I identified the bug, but couldn't solve it yet. It is here: https://github.com/OpenSecuritySummit/oss2019/blob/bd21b0bc167783d6750dbfce1cf762b7b2f7163e/layouts/partials/schedule/track-tr-time.html#L10

That's because we need to split and range over it. I have a fix semi-working, will try to push it soon.
